[keyboard]
name = "soflev2-rmk"
product_name = "soflev2-rmk"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "bhe"
chip = "nrf52840"

[layout]
matrix_map = """
            (0,0) (0,1) (0,2) (0,3) (0,4) (0,5)                  (0,7) (0,8) (0,9) (0,10) (0,11) (0,12)
            (1,0) (1,1) (1,2) (1,3) (1,4) (1,5)                  (1,7) (1,8) (1,9) (1,10) (1,11) (1,12)
            (2,0) (2,1) (2,2) (2,3) (2,4) (2,5)                  (2,7) (2,8) (2,9) (2,10) (2,11) (2,12)
            (3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6)  (4,8) (3,7) (3,8) (3,9) (3,10) (3,11) (3,12)
            (4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6)  (4,9) (4,10)                         (4,11) (4,12)

"""
rows = 6
cols = 12
layers = 5
keymap = [
    # LBASE layer
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backspace"],
        ["Tab", "Q", "W", "E", "R", "T",                                            "Y", "U", "I", "O", "P", "Backslash"],
        ["LCtrl", "MT(A, LCtrl)", "MT(S,LAlt)", "MT(D,LGui)", "MT(F, LShift)",      "G",    "H", "MT(J,RShift)", "MT(K,RGui)", "MT(L, RAlt)", "MT(Semicolon, RCtrl)", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B",                                         "N", "M", "Comma", "Dot", "Slash", "MT(Grave, RShift)"],
        ["Kc1", "LAlt", "LGui", "MO(1)", "LT(3, Space)", "Kc1",                       "__", "Enter", "MO(2)", "LeftBracket", "RightBracket", "Kc1"]
    ],
     # LLOWER layer (Layer 2)
     [
         ["_", "_", "_", "_", "_", "__", "__", "_", "_", "_", "_", "_"],
         ["__", "WM(Kc1, LShift)", "WM(Kc2, LShift)", "WM(Kc3, LShift)", "WM(Kc4, LShift)", "WM(Kc5, LShift)", "WM(Kc6, LShift)", "WM(Kc7, LShift)", "WM(Kc8, LShift)", "WM(Kc9, LShift)", "WM(Kc0, LShift)", "_"],
         ["_", "_", "_", "_", "_", "_",             "Backspace", "WM(Minus, LShift)", "WM(Equal, LShift)", "WM(LeftBracket, LShift)", "WM(RightBracket, LShift)", "_"],
         ["_", "F7", "F8", "F9", "Tab", "F6", "WM(LeftBracket, LShift)", "WM(RightBracket, LShift)", "WM(Comma, LShift)", "WM(Dot, LShift)", "WM(Slash, LShift)", "WM(Grave, LShift)"],
         ["Kc2", "_", "_", "_", "_", "__", "__", "_", "_", "_", "_", "Kc2"]
     ],
     #LRAISE layer (Layer 3)
     [
         ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
         ["_", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "WM(Backslash, LShift)"],
         ["_", "F1", "F2", "F3", "F4", "F5",        "F6", "Minus", "Equal", "LeftBracket", "RightBracket", "_"],
         ["_", "F7", "F8", "F9", "F10", "F11",      "F12", "RightBracket", "Comma", "Dot", "Slash", "Grave"],
         ["Kc3", "_", "_", "_", "_", "__", "__", "_", "_", "_", "_", "Kc3"]
     ],
    
    
     # LFUNC layer (Layer 4)
     [
         ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
         ["__", "_", "_", "MouseUp",  "PageUp", "PageDown",                      "_", "MouseWheelUp", "MouseWheelDown", "__", "__", "__"],
         ["_",      "_", "MouseLeft", "MouseDown", "MouseRight","__",              "Left", "Down", "UP", "Right", "__", "__"],
         ["_", "_", "_", "_","Home", "End",                    "MouseBtn1", "MouseBtn2", "Comma", "Dot", "Slash", "RShift"],
         ["Kc4", "_", "_", "_", "_", "__", "__", "_", "_", "_", "_", "Kc4"]
     ],
    
     # LDEBUG layer (Layer 5)
     [
         ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
         ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
         ["_", "__", "__", "DebugToggle", "__", "F6", "Left", "Down", "UP", "Down", "Semicolon", "Quote"],
         ["_", "Z", "X", "C", "Home", "Bootloader", "N", "M", "Comma", "Dot", "Slash", "RShift"],
         ["Kc5", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "Kc5"]
     ]
]

[storage]

enabled = true
# Set `clear_storage` to true to clear all the stored info when the keyboard boots
clear_storage = true

[ble]

enabled = true

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms"}

[split]

connection = "ble"

[split.central]

rows = 5
cols = 7
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

## nice nanov2 pin info https://www.nologo.tech/product/otherboard/NRF52840.html#%E4%BA%A7%E5%93%81%E5%8F%82%E6%95%B0
## pin 1 0
#serial = [{ instance = "UART0", tx_pin = "P0_06", rx_pin = "P0_08" }]

[split.central.matrix]

## promicro pin: 4 5 6 7 8
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04"]
## promicro pin: 21 20  19 18 15 14 16 
output_pins = ["P0_31", "P0_29","P0_02", "P1_15", "P1_13", "P1_11", "P0_10" ]

[[split.peripheral]]

rows = 5
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
#serial = [{ instance = "UART0", tx_pin = "P0_06", rx_pin = "P0_08" }]

[split.peripheral.matrix]

## promicro pin: 3 4 5 6 7
input_pins = ["P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]
## promicro pin: 9 8 18 19 20 21
output_pins = ["P1_16", "P1_04", "P1_15", "P0_02", "P0_29", "P0_31"]



